language: generic
sudo: required


services:
    - docker

before_install:
    - docker build -t kamserg1608/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true kamserg1608/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "doker-react"
    env: "DokerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-155669391012"
    bucket_path: "doker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY