language: generic
sudo: required


services:
    - docker

before_install:
    - docker build -t kamserg1608/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true kamserg1608/docker-react npm run test